# Goal
uint8 DIRECTION_ROLL=1
uint8 DIRECTION_PITCH=2
uint8 DIRECTION_YAW=3
uint8 STOP=4
uint8 direction
uint32 value # Number of units (time, number of tiles) to rotate till. 0 means inifinite rotate mode.
---
# Result
uint32 totalValue # Number of passed units
---
# Feedback
uint32 currentValue # Number of currently passed units