// Generated by gencpp from file auv_vision/gate_msg.msg
// DO NOT EDIT!


#ifndef AUV_VISION_MESSAGE_GATE_MSG_H
#define AUV_VISION_MESSAGE_GATE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auv_vision
{
template <class ContainerAllocator>
struct gate_msg_
{
  typedef gate_msg_<ContainerAllocator> Type;

  gate_msg_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)  {
    }
  gate_msg_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , x3(0.0)
    , y3(0.0)
    , x4(0.0)
    , y4(0.0)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _x3_type;
  _x3_type x3;

   typedef float _y3_type;
  _y3_type y3;

   typedef float _x4_type;
  _x4_type x4;

   typedef float _y4_type;
  _y4_type y4;





  typedef boost::shared_ptr< ::auv_vision::gate_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auv_vision::gate_msg_<ContainerAllocator> const> ConstPtr;

}; // struct gate_msg_

typedef ::auv_vision::gate_msg_<std::allocator<void> > gate_msg;

typedef boost::shared_ptr< ::auv_vision::gate_msg > gate_msgPtr;
typedef boost::shared_ptr< ::auv_vision::gate_msg const> gate_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auv_vision::gate_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auv_vision::gate_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auv_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'auv_vision': ['/home/sibirsky/factory/AUV-fork/src/auv_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auv_vision::gate_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auv_vision::gate_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_vision::gate_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auv_vision::gate_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_vision::gate_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auv_vision::gate_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auv_vision::gate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f52529f33ffcb369c5aa2cf50823e6d";
  }

  static const char* value(const ::auv_vision::gate_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f52529f33ffcb36ULL;
  static const uint64_t static_value2 = 0x9c5aa2cf50823e6dULL;
};

template<class ContainerAllocator>
struct DataType< ::auv_vision::gate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auv_vision/gate_msg";
  }

  static const char* value(const ::auv_vision::gate_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auv_vision::gate_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n\
float32 y1\n\
float32 x2\n\
float32 y2\n\
float32 x3\n\
float32 y3\n\
float32 x4\n\
float32 y4\n\
";
  }

  static const char* value(const ::auv_vision::gate_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auv_vision::gate_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.x3);
      stream.next(m.y3);
      stream.next(m.x4);
      stream.next(m.y4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gate_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auv_vision::gate_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auv_vision::gate_msg_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    s << indent << "x3: ";
    Printer<float>::stream(s, indent + "  ", v.x3);
    s << indent << "y3: ";
    Printer<float>::stream(s, indent + "  ", v.y3);
    s << indent << "x4: ";
    Printer<float>::stream(s, indent + "  ", v.x4);
    s << indent << "y4: ";
    Printer<float>::stream(s, indent + "  ", v.y4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUV_VISION_MESSAGE_GATE_MSG_H
